### PR TITLE
Updated obsolete Paket API use

### PR DESCRIPTION
**Pull request by eugene-g**
generate-include-scripts is obsolete, replaced by generate-load-scripts

https://fsprojects.github.io/Paket/paket-generate-include-scripts.html
https://fsprojects.github.io/Paket/paket-generate-load-scripts.html

Didn't try to build and test, sorry.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
It also needs changes in package.json, since you've changed commandID

**Comment by eugene-g** [comment]
Roger that. Will do after working day is done.

**Comment by eugene-g** [comment]
Bump :)

**Comment by Krzysztof-Cieslak** [comment]
Duh, thanks for the reminder.

**Pull request merged**
