### PR TITLE
Also search binaries in the root of the workspace

### PR DESCRIPTION
**Pull request by vbfox**
I need to fully test it in more configurations.

But it allow to place paket.exe directly in the workspace directory (Well most of the time it's the Magic mode bootstrapper)

It also allow to place the normal boostrapper / paket.exe pair in the workspace directory even if I think that nobody does that.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Is it still WIP?

**Comment by vbfox** [comment]
I rebased it on the current master & did the test I wanted, seem ok :)

**Comment by Krzysztof-Cieslak** [comment]
Thanks :)

**Comment by Krzysztof-Cieslak** [comment]
Released in `1.7.1`

**Pull request merged**
