### PR TITLE
WIP: Creating a FAKE script to publish to VS Code gallery

### PR DESCRIPTION
**Pull request by forki**
Implements https://github.com/ionide/ionide-vscode-paket/issues/4
- [x] - detect where node lives
- [x] - Install VSCE
- [ ] - Login in VSCE (waitng for https://github.com/Microsoft/vscode-vsce/pull/47 - but since it's only one time thingy it can be done manually)
- [x] - Update version in package.json from ReleaseNotes.md
- [x] - Create vsix package
- [x] - push vsix to github releases
- [x] - publish to Visual Stuido Code gallery

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
I think local npm installation (obtained by Paket from NuGet can be uesd on Windows) - https://github.com/FractalProject/Fractal.Sample/blob/master/build.fsx#L42-L45

**Comment by forki** [comment]
Awesome ;-)

**Comment by Krzysztof-Cieslak** [comment]
Also, preferably during deploy process I would want to publish plugin to extension gallery but also do GitHub release of packed version (using `vsce package`)

**Comment by forki** [comment]
image

**Comment by forki** [comment]
waiting for https://github.com/Microsoft/vscode-vsce/pull/47 to get merged and released ;-)

**Comment by forki** [comment]
done!

see https://github.com/ionide/ionide-vscode-paket/releases/tag/1.0.2

**Comment by forki** [comment]
This is my release.cmd (minus passwords). It's already in gitignore.

```
    @echo off
    cls

    .paket\paket.bootstrapper.exe
    if errorlevel 1 (
    exit /b %errorlevel%
    )

    .paket\paket.exe restore
    if errorlevel 1 (
    exit /b %errorlevel%
    )
    packages\FAKE\tools\FAKE.exe build.fsx "target=Release" "vsce-publisher=mypublisher" "vsce-token=mykey" "github-user=myuser" "github-pw=mypw"
```

**Comment by Krzysztof-Cieslak** [comment]
1. VSCE path is hard coded  to your path, I wonder if we could use `%APPDATA%` to get `C:\Users\Steffen\AppData\Roaming` this part of VSCE path.
2. I'm not sure if `InstallVSCE` and `loginToVSCE` should part of normal release cycle - those operations have to be done only once per machine, so while it is useful to have them in build script, i would not include them in normal release path, but rater create target `Setup` which will just run those 2.

**Comment by forki** [comment]
1. Oups. fixed
2. Mhm these targets run for only two seconds. It makes it really convenient ;-)

**Comment by Krzysztof-Cieslak** [comment]
Well, we don't know how vsce login will behave. I think it is asking for confirmation in case of relogging.

**Comment by forki** [comment]
Yeah we can decide later. At the moment it's not in standard pipeline.

**Comment by Krzysztof-Cieslak** [comment]
OK, so let's do this ;)

**Pull request merged**
